<table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; font-family: Vazirmatn, sans-serif;">
  <thead">
    <tr>
      <th>نام پارامتر</th>
      <th>نوع داده</th>
      <th>توضیح کاربرد</th>
      <th>مقدار پیش‌فرض</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>by</code></td>
      <td>str یا list</td>
      <td>نام ستون یا لیستی از ستون‌ها برای مرتب‌سازی</td>
      <td>ضروری است</td>
    </tr>
    <tr>
      <td><code>ascending</code></td>
      <td>bool یا list</td>
      <td>مرتب‌سازی صعودی (True) یا نزولی (False)</td>
      <td><code>True</code></td>
    </tr>
    <tr>
      <td><code>inplace</code></td>
      <td>bool</td>
      <td>اگر <code>True</code> باشد، دیتافریم اصلی تغییر می‌کند</td>
      <td><code>False</code></td>
    </tr>
    <tr>
      <td><code>axis</code></td>
      <td>int</td>
      <td>محور مرتب‌سازی: <code>0</code> برای سطرها، <code>1</code> برای ستون‌ها</td>
      <td><code>0</code></td>
    </tr>
    <tr>
      <td><code>na_position</code></td>
      <td>str</td>
      <td>جایگاه مقادیر گمشده: <code>'first'</code> یا <code>'last'</code></td>
      <td><code>'last'</code></td>
    </tr>
    <tr>
      <td><code>kind</code></td>
      <td>str</td>
      <td>نوع الگوریتم مرتب‌سازی: <code>'quicksort'</code>, <code>'mergesort'</code>, <code>'heapsort'</code>, <code>'stable'</code></td>
      <td><code>'quicksort'</code></td>
    </tr>
    <tr>
      <td><code>ignore_index</code></td>
      <td>bool</td>
      <td>اگر <code>True</code> باشد، ایندکس جدید تولید می‌شود</td>
      <td><code>False</code></td>
    </tr>
  </tbody>
</table>

## Import Libraries

In [53]:
import numpy as np 
import pandas as pd

## Load the Data

In [54]:
df = pd.read_csv('Top Ranked Real Movies Dataset.csv')
df.info()
display(df.head(3))

<class 'pandas.DataFrame'>
RangeIndex: 1002 entries, 0 to 1001
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          1002 non-null   int64
 1   Movie Name          1002 non-null   str
 2   Year of Release     1002 non-null   str
 3   Watch Time          1002 non-null   str
 4   Movie Rating        1002 non-null   float64
 5   Meatscore of movie  838 non-null    float64
 6   Votes               1002 non-null   str
 7   Gross               851 non-null    str
 8   Description         1002 non-null   str
dtypes: float64(2), int64(1), str(6)
memory usage: 70.6 KB

,Unnamed: 0,Movie Name,Year of Release,Watch Time,Movie Rating,Meatscore of movie,Votes,Gross,Description
0,0,Jai Bhim,-2021,164 min,9.4,NaN,"180,702",NaN,When a tribal man is arrested for a case of al...
1,1,Soorarai Pottru,-2020,153 min,9.3,NaN,"108,490",NaN,"Nedumaaran Rajangam ""Maara"" sets out to make t..."
2,2,The Shawshank Redemption,-1994,142 min,9.3,81.0,"2,559,534",$28.34M,Two imprisoned men bond over a number of years...

In [55]:
df = df.drop(columns=['Unnamed: 0'])

In [56]:
df['Year of Release'] = df['Year of Release'].str.extract(r'(\d{4})')
df['Year of Release'] = pd.to_numeric(df['Year of Release'],errors= 'coerce')

df['Votes'] = df['Votes'].str.replace(',','')
df['Votes']= pd.to_numeric(df['Votes'],errors='coerce')

## Sorting Logic

In [57]:
#df.sort_values(by='Votes', ascending= True)
# df = df.sort_values(by='Votes', ascending= False)
df.sort_values(by='Votes', ascending= False, inplace=True)

In [58]:
df.sort_values(by='Votes', ascending= True, ignore_index=True)

,Movie Name,Year of Release,Watch Time,Movie Rating,Meatscore of movie,Votes,Gross,Description
0,Taylor Swift Reputation Stadium Tour,2018,125 min,8.4,71.0,7459,NaN,"Reputation is a tribute to her epic ambition, ..."
1,Taylor Swift: The Eras Tour,2023,169 min,8.2,83.0,17000,$261.60M,Designed as a tribute to Swift's discography a...
2,Vera Drake,2004,125 min,7.7,83.0,25243,$3.75M,Abortionist Vera Drake finds her beliefs and p...
3,Sarfarosh,1999,174 min,8.1,NaN,25329,NaN,After his brother is killed and father severel...
4,Il gattopardo,1963,186 min,8.0,100.0,25351,NaN,"The Prince of Salina, a noble aristocrat of im..."
...,...,...,...,...,...,...,...,...
997,Forrest Gump,1994,142 min,8.8,82.0,1974976,$330.25M,"The presidencies of Kennedy and Johnson, the V..."
998,Fight Club,1999,139 min,8.8,66.0,2014657,$37.03M,An insomniac office worker and a devil-may-car...
999,Inception,2010,148 min,8.8,74.0,2247417,$292.58M,A thief who steals corporate secrets through t...
1000,The Dark Knight,2008,152 min,9.1,84.0,2519388,$534.86M,When the menace known as the Joker wreaks havo...
1001,The Shawshank Redemption,1994,142 min,9.3,81.0,2559534,$28.34M,Two imprisoned men bond over a number of years...

In [59]:
df.sort_values(by=['Votes','Movie Rating'],ascending=[False,True])

,Movie Name,Year of Release,Watch Time,Movie Rating,Meatscore of movie,Votes,Gross,Description
2,The Shawshank Redemption,1994,142 min,9.3,81.0,2559534,$28.34M,Two imprisoned men bond over a number of years...
4,The Dark Knight,2008,152 min,9.1,84.0,2519388,$534.86M,When the menace known as the Joker wreaks havo...
13,Inception,2010,148 min,8.8,74.0,2247417,$292.58M,A thief who steals corporate secrets through t...
16,Fight Club,1999,139 min,8.8,66.0,2014657,$37.03M,An insomniac office worker and a devil-may-car...
17,Forrest Gump,1994,142 min,8.8,82.0,1974976,$330.25M,"The presidencies of Kennedy and Johnson, the V..."
...,...,...,...,...,...,...,...,...
452,Il gattopardo,1963,186 min,8.0,100.0,25351,NaN,"The Prince of Salina, a noble aristocrat of im..."
282,Sarfarosh,1999,174 min,8.1,NaN,25329,NaN,After his brother is killed and father severel...
802,Vera Drake,2004,125 min,7.7,83.0,25243,$3.75M,Abortionist Vera Drake finds her beliefs and p...
1001,Taylor Swift: The Eras Tour,2023,169 min,8.2,83.0,17000,$261.60M,Designed as a tribute to Swift's discography a...
1000,Taylor Swift Reputation Stadium Tour,2018,125 min,8.4,71.0,7459,NaN,"Reputation is a tribute to her epic ambition, ..."