## Import Librsries

In [47]:
import pandas as pd
import numpy as np

## Load the Data

In [48]:
df = pd.read_csv('Top Ranked Real Movies Dataset.csv')
df.info()
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 1002 entries, 0 to 1001
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          1002 non-null   int64
 1   Movie Name          1002 non-null   str
 2   Year of Release     1002 non-null   str
 3   Watch Time          1002 non-null   str
 4   Movie Rating        1002 non-null   float64
 5   Meatscore of movie  838 non-null    float64
 6   Votes               1002 non-null   str
 7   Gross               851 non-null    str
 8   Description         1002 non-null   str
dtypes: float64(2), int64(1), str(6)
memory usage: 70.6 KB

,Unnamed: 0,Movie Name,Year of Release,Watch Time,Movie Rating,Meatscore of movie,Votes,Gross,Description
0,0,Jai Bhim,-2021,164 min,9.4,NaN,"180,702",NaN,When a tribal man is arrested for a case of al...
1,1,Soorarai Pottru,-2020,153 min,9.3,NaN,"108,490",NaN,"Nedumaaran Rajangam ""Maara"" sets out to make t..."
2,2,The Shawshank Redemption,-1994,142 min,9.3,81.0,"2,559,534",$28.34M,Two imprisoned men bond over a number of years...
3,3,The Godfather,-1972,175 min,9.2,100.0,"1,761,949",$134.97M,The aging patriarch of an organized crime dyna...
4,4,The Dark Knight,-2008,152 min,9.1,84.0,"2,519,388",$534.86M,When the menace known as the Joker wreaks havo...

In [49]:
df.drop(columns=['Unnamed: 0'])
df.head()

,Unnamed: 0,Movie Name,Year of Release,Watch Time,Movie Rating,Meatscore of movie,Votes,Gross,Description
0,0,Jai Bhim,-2021,164 min,9.4,NaN,"180,702",NaN,When a tribal man is arrested for a case of al...
1,1,Soorarai Pottru,-2020,153 min,9.3,NaN,"108,490",NaN,"Nedumaaran Rajangam ""Maara"" sets out to make t..."
2,2,The Shawshank Redemption,-1994,142 min,9.3,81.0,"2,559,534",$28.34M,Two imprisoned men bond over a number of years...
3,3,The Godfather,-1972,175 min,9.2,100.0,"1,761,949",$134.97M,The aging patriarch of an organized crime dyna...
4,4,The Dark Knight,-2008,152 min,9.1,84.0,"2,519,388",$534.86M,When the menace known as the Joker wreaks havo...

## Data Analysis

In [50]:
high_ranked_movies = df.loc[df['Movie Rating'] > 9,['Movie Name','Movie Rating']]
high_ranked_movies

                 Movie Name  Movie Rating
0                  Jai Bhim           9.4
1           Soorarai Pottru           9.3
2  The Shawshank Redemption           9.3
3             The Godfather           9.2
4           The Dark Knight           9.1

In [51]:
df['Year of Release'] = df['Year of Release'].str.extract(r'(\d{4})')
df['Year of Release'] = pd.to_numeric(df['Year of Release'], errors = 'coerce')

df['Votes'] = df['Votes'].str.replace(',','')
df['Votes'] = pd.to_numeric(df['Votes'], errors = 'coerce')

In [54]:
selected_movies = df.loc[(df['Year of Release'] > 2015) & (df['Votes'] > 1_000_00)]
selected_movies

,Unnamed: 0,Movie Name,Year of Release,Watch Time,Movie Rating,Meatscore of movie,Votes,Gross,Description
0,0,Jai Bhim,2021,164 min,9.4,NaN,180702,NaN,When a tribal man is arrested for a case of al...
1,1,Soorarai Pottru,2020,153 min,9.3,NaN,108490,NaN,"Nedumaaran Rajangam ""Maara"" sets out to make t..."
10,10,Shershaah,2021,135 min,8.9,NaN,114701,NaN,The story of PVC awardee Indian soldier Capt. ...
29,29,Spider-Man: No Way Home,2021,148 min,8.6,71.0,518443,#56,"With Spider-Man's identity now revealed, Peter..."
46,46,Gisaengchung,2019,132 min,8.5,96.0,726006,$53.37M,Greed and class discrimination threaten the ne...
...,...,...,...,...,...,...,...,...,...
914,914,Baby Driver,2017,113 min,7.6,86.0,504364,$107.83M,After being coerced into working for a crime b...
916,916,Incredibles 2,2018,118 min,7.6,80.0,281318,$608.58M,The Incredibles family takes on a new mission ...
917,917,Moana,2016,107 min,7.6,81.0,315403,$248.76M,"In Ancient Polynesia, when a terrible curse in..."
920,920,Hell or High Water,2016,102 min,7.6,88.0,222969,$26.86M,A divorced father and his ex-con older brother...
926,926,A Star Is Born,2018,136 min,7.6,88.0,369722,$215.29M,A musician helps a young singer find fame as a...