## Import Librsries

In [2]:
import pandas as pd
import numpy as np

## Load the Data

In [3]:
df = pd.read_csv('Top Ranked Real Movies Dataset.csv')
df.info()
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 1002 entries, 0 to 1001
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          1002 non-null   int64
 1   Movie Name          1002 non-null   str
 2   Year of Release     1002 non-null   str
 3   Watch Time          1002 non-null   str
 4   Movie Rating        1002 non-null   float64
 5   Meatscore of movie  838 non-null    float64
 6   Votes               1002 non-null   str
 7   Gross               851 non-null    str
 8   Description         1002 non-null   str
dtypes: float64(2), int64(1), str(6)
memory usage: 70.6 KB

,Unnamed: 0,Movie Name,Year of Release,Watch Time,Movie Rating,Meatscore of movie,Votes,Gross,Description
0,0,Jai Bhim,-2021,164 min,9.4,NaN,"180,702",NaN,When a tribal man is arrested for a case of al...
1,1,Soorarai Pottru,-2020,153 min,9.3,NaN,"108,490",NaN,"Nedumaaran Rajangam ""Maara"" sets out to make t..."
2,2,The Shawshank Redemption,-1994,142 min,9.3,81.0,"2,559,534",$28.34M,Two imprisoned men bond over a number of years...
3,3,The Godfather,-1972,175 min,9.2,100.0,"1,761,949",$134.97M,The aging patriarch of an organized crime dyna...
4,4,The Dark Knight,-2008,152 min,9.1,84.0,"2,519,388",$534.86M,When the menace known as the Joker wreaks havo...

In [4]:
df.drop(columns=['Unnamed: 0'])
df.head()

,Unnamed: 0,Movie Name,Year of Release,Watch Time,Movie Rating,Meatscore of movie,Votes,Gross,Description
0,0,Jai Bhim,-2021,164 min,9.4,NaN,"180,702",NaN,When a tribal man is arrested for a case of al...
1,1,Soorarai Pottru,-2020,153 min,9.3,NaN,"108,490",NaN,"Nedumaaran Rajangam ""Maara"" sets out to make t..."
2,2,The Shawshank Redemption,-1994,142 min,9.3,81.0,"2,559,534",$28.34M,Two imprisoned men bond over a number of years...
3,3,The Godfather,-1972,175 min,9.2,100.0,"1,761,949",$134.97M,The aging patriarch of an organized crime dyna...
4,4,The Dark Knight,-2008,152 min,9.1,84.0,"2,519,388",$534.86M,When the menace known as the Joker wreaks havo...

## Data Analysis

In [5]:
high_ranked_movies = df.loc[df['Movie Rating'] > 9,['Movie Name','Movie Rating']]
high_ranked_movies

                 Movie Name  Movie Rating
0                  Jai Bhim           9.4
1           Soorarai Pottru           9.3
2  The Shawshank Redemption           9.3
3             The Godfather           9.2
4           The Dark Knight           9.1

In [ ]:
df['Year of Release'] = df['Year of Release'].str.extract(r'(\d{4})')  #4 raghsm adadi
df['Year of Release'] = pd.to_numeric(df['Year of Release'], errors = 'coerce')

df['Votes'] = df['Votes'].str.replace(',','')
df['Votes'] = pd.to_numeric(df['Votes'], errors = 'coerce')

In [7]:
selected_movies = df.loc[(df['Year of Release'] > 2015) & (df['Votes'] > 1_000_00),['Movie Name','Year of Release','Votes']].head(10)
selected_movies

                           Movie Name  Year of Release    Votes
0                            Jai Bhim             2021   180702
1                     Soorarai Pottru             2020   108490
10                          Shershaah             2021   114701
29            Spider-Man: No Way Home             2021   518443
46                       Gisaengchung             2019   726006
48             Avengers: Infinity War             2018   992026
73                              Joker             2019  1160925
75                     Kimi no na wa.             2016   244361
76                             Dangal             2016   179724
77  Spider-Man: Into the Spider-Verse             2018   477205

In [19]:
Votes = df['Votes'].to_numpy()
Movie_Rating = df['Movie Rating'].to_numpy()
print(f'average of Votes: {np.mean(Votes)}')
print(f'std of votes : {np.std(Votes)}')
print(f'min of votes : {np.min(Votes)}')
print(f'max of votes : {np.max(Votes)}')

print('----------------------')
      
print(f'average of Movie rating: {np.mean(Movie_Rating)}')
print(f'std of Movie_Rating : {np.std(Movie_Rating)}')
print(f'min of Movie_Rating : {np.min(Movie_Rating)}')
print(f'max of Movie_Rating : {np.max(Movie_Rating)}')

average of Votes: 298884.1027944112
std of votes : 354327.86857368203
min of votes : 7459
max of votes : 2559534
----------------------
average of Movie rating: 7.976746506986029
std of Movie_Rating : 0.2916129581791907
min of Movie_Rating : 7.6
max of Movie_Rating : 9.4