## Import Libraries

In [1]:
import numpy as np
import pandas as pd

## Data Frame

In [3]:
my_dict = {
    'Name': ['Fardin','Hasti','Ali','Farya'],
    'Age':[23,23,26,17],
    'City':['Kerman','Gilan','Esfahan','Ahvaz']
}
df = pd.DataFrame(my_dict)
df

     Name  Age     City
0  Fardin   23   Kerman
1   Hasti   23    Gilan
2     Ali   26  Esfahan
3   Farya   17    Ahvaz

In [ ]:
print(df.iloc[1,2])      #iloc faghat Adad
print(df.loc[1,'City'])

Gilan
Gilan

In [45]:
print(df['Name'])
print(df[['Name','City']])     # listayr too dar too

0    Fardin
1     Hasti
2       Ali
3     Farya
Name: Name, dtype: str
     Name     City
0  Fardin   Kerman
1   Hasti    Gilan
2     Ali  Esfahan
3   Farya    Ahvaz

In [ ]:
print(df.iloc[0])
print('\n--------\n')             
print(df.iloc[0:2])

Name    Fardin
Age         23
City    Kerman
Name: 0, dtype: object

--------

     Name  Age    City
0  Fardin   23  Kerman
1   Hasti   23   Gilan

In [13]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'Age', 'City'], dtype='str')

In [7]:
my_list = [
    ['Fardin',23,'Kerman'],
    ['Hasti',23,'Gilan'],
    ['Ali',26,'Esfahan'],
    ['Farya',17,'Ahvaz']
]
df2 = pd.DataFrame(my_list)
df2

        0   1        2
0  Fardin  23   Kerman
1   Hasti  23    Gilan
2     Ali  26  Esfahan
3   Farya  17    Ahvaz

In [ ]:
print(df2[0])

print('\n--------\n')

print(df2.iloc[1,1])

0    Fardin
1     Hasti
2       Ali
3     Farya
Name: 0, dtype: str

--------

23

In [16]:
print(df2.index)
print(df2.columns)

RangeIndex(start=0, stop=4, step=1)
RangeIndex(start=0, stop=3, step=1)

In [10]:
my_array = np.array([
    ['Fardin',23,'Kerman'],
    ['Hasti',23,'Gilan'],
    ['Ali',26,'Esfahan'],
    ['Farya',17,'Ahvaz']
])
df3 = pd.DataFrame(my_array)
df3

        0   1        2
0  Fardin  23   Kerman
1   Hasti  23    Gilan
2     Ali  26  Esfahan
3   Farya  17    Ahvaz

In [17]:
print(df3.index)
print(df3.columns)

RangeIndex(start=0, stop=4, step=1)
RangeIndex(start=0, stop=3, step=1)